// Package webui carries the chat frontend inside the binary.
//
// # WHY THIS EXISTS
//
// The frontend used to live only on disk, in a web/ directory beside the
// executable, found automatically by config.detectWebRoot(). That made the app
// two halves a user could update separately — and given how 1.7.x is actually
// distributed, they always did. A zip dropped over an install replaced
// chat.html, js/ and css/ at the install root; the server went on serving the
// OLD copy under web/, because web/ won the search order and nothing compared
// the two. Every server-side feature of the release then looked missing, and
// the page had no way to tell "your binary is old" from "your page is old".
//
// The frontend now ships inside the executable. One file to replace, and the
// two halves cannot disagree, because there is only one artifact to disagree
// with.
//
// A disk directory is still honoured — but only when web_root names it, never
// by discovery. That is the whole point: a leftover web/ from an older install
// can no longer shadow the binary's own copy. And a file missing from an
// override falls through to the built-in copy, so a half-populated mod
// directory gives a modified page rather than a blank one with console errors.
package webui

import (
	"embed"
	"errors"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// The staged frontend. assets/ is generated by stage-web.sh and gitignored, the
// same arrangement web/ had and for the same reason: the repo root stays the
// single source of truth for the frontend, so an upstream merge lands in one
// place instead of two.
//
// "all:" so the directory is embedded even when it holds only .gitkeep, which
// is what a fresh clone that has never run stage-web.sh looks like. That build
// is legal and Staged() reports false for it; the server then falls back to
// serving the repo root from disk, exactly as a dev checkout did before.
//
//go:embed all:assets
var embedded embed.FS

// Built is the embedded frontend, rooted where chat.html lives.
func Built() fs.FS {
	sub, err := fs.Sub(embedded, "assets")
	if err != nil {
		// Only reachable if the embed directive above is edited to name a
		// directory that is not there, which does not compile. Returning the
		// unrooted FS keeps this honest rather than panicking in a server.
		return embedded
	}
	return sub
}

// Staged reports whether the binary was built with a real frontend in it.
//
// False means someone built from a checkout without running stage-web.sh. That
// is a supported developer state, not an error — the caller falls back to disk.
func Staged() bool {
	_, err := fs.Stat(Built(), "chat.html")
	return err == nil
}

// Overlay layers a disk directory over the built-in frontend: dir wins where it
// has the file, the binary answers where it does not.
//
// The directory is opened through os.Root, so a symlink inside it that points
// outside cannot be read through the server. The textual traversal checks in
// this package's Resolve are the first gate; this is the one that holds when a
// path passes every string test and the filesystem itself is the trick.
func Overlay(dir string) (fs.FS, error) {
	root, err := os.OpenRoot(dir)
	if err != nil {
		return nil, err
	}
	return layered{over: root.FS(), under: Built()}, nil
}

// layered tries over, then under. Nothing is cached: an override exists so
// someone can edit a file and reload, and a cache would make that not work.
type layered struct {
	over  fs.FS
	under fs.FS
}

func (l layered) Open(name string) (fs.File, error) {
	if l.over != nil {
		if f, err := l.over.Open(name); err == nil {
			return f, nil
		} else if !errors.Is(err, fs.ErrNotExist) {
			// A permission error on an override file is worth surfacing rather
			// than papering over with the built-in copy: the user put that file
			// there on purpose and would otherwise never learn it is unreadable.
			return nil, err
		}
	}
	return l.under.Open(name)
}

// uiStampRe matches the frontend's own build stamp, js/01-config.js's
// GOBBONET_UI_VERSION. Single or double quotes, because it is hand-edited.
var uiStampRe = regexp.MustCompile(`GOBBONET_UI_VERSION\s*=\s*['"]([^'"]+)['"]`)

// Stamp reads the frontend's build stamp out of the given filesystem, or "" if
// it cannot be found.
//
// Only interesting when an override is active. For the built-in copy the page
// and the server are the same file and cannot disagree — which is the property
// this package exists to create. An override reintroduces the possibility, so
// the server checks it at boot and says so rather than leaving the user to find
// out from a feature that silently does nothing.
func Stamp(fsys fs.FS) string {
	f, err := fsys.Open("js/01-config.js")
	if err != nil {
		return ""
	}
	defer f.Close()
	// The stamp is in the file's header comment block; 8 KiB reaches it with
	// room to spare and bounds what a hostile override can make us read.
	buf, err := io.ReadAll(io.LimitReader(f, 8<<10))
	if err != nil {
		return ""
	}
	if m := uiStampRe.FindSubmatch(buf); m != nil {
		return string(m[1])
	}
	return ""
}

// stampName records which build wrote an exported tree. A dot name, so
// internal/static refuses to serve it (see dotfileRe there) -- it is
// bookkeeping, not content.
const stampName = ".gobbonet-ui"

// Export writes the built-in frontend to dir as ordinary files.
//
// # WHY THE FILES ARE ON DISK AT ALL
//
// Compiling the frontend in fixed the update story -- one file to replace, two
// halves that cannot disagree -- and cost something real: an install no longer
// contained the interface it was serving. You could not read it, edit it, or
// check that what the server sent matched what shipped. "Plainly viewable"
// means visible where the thing is unpacked; anything else is not auditable.
//
// So the binary writes them out, and serves them from there. The copy on disk
// is the copy being served, not a decorative mirror.
//
// WHY THIS CANNOT BRING BACK THE STALE-web/ BUG
//
// That bug was a directory the server FOUND and trusted. This is a directory
// the server OWNS: the stamp records which build wrote it, and a build that
// does not recognise its own stamp rewrites the whole tree before serving a
// byte of it. A leftover from an older install is therefore replaced, not
// obeyed, which is the exact opposite of what used to happen.
//
// Returns the number of files written, or an error the caller should treat as
// non-fatal: a read-only install directory is normal (Program Files,
// /usr/lib/gobbonet) and the right answer there is to serve from the binary and
// say so, not to refuse to start.
func Export(dir, version string) (int, error) {
	if !Staged() {
		return 0, errors.New("this build has no frontend compiled into it")
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return 0, err
	}

	built := Built()
	written := 0
	err := fs.WalkDir(built, ".", func(name string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		target := filepath.Join(dir, filepath.FromSlash(name))
		if d.IsDir() {
			if name == "." {
				return nil
			}
			return os.MkdirAll(target, 0o755)
		}
		// The keep-file is a build artifact of the embed, not part of the
		// frontend, and writing it into a user's folder would just puzzle them.
		if name == ".gitkeep" {
			return nil
		}
		data, err := fs.ReadFile(built, name)
		if err != nil {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		// 0644: these are served to a browser and read by whoever owns the
		// machine. Same rule stage-web.sh applies to the staged tree.
		if err := os.WriteFile(target, data, 0o644); err != nil {
			return err
		}
		written++
		return nil
	})
	if err != nil {
		return written, err
	}

	// The stamp is written LAST, so an export interrupted half way leaves a
	// stamp that does not match and is redone on the next start rather than
	// being mistaken for a complete tree.
	stamp := "This folder is written by GobboNet and is the chat interface it serves.\n" +
		"version=" + version + "\n\n" +
		"Edit these files and reload the page to see your changes.\n" +
		"They are REPLACED when the version above changes -- that is how an update\n" +
		"reaches the interface. To keep edits across updates, copy them somewhere\n" +
		"else and point GobboNet at that folder instead:\n\n" +
		"    gobbonet config set web_root /path/to/your/copy\n"
	if err := os.WriteFile(filepath.Join(dir, stampName), []byte(stamp), 0o644); err != nil {
		return written, err
	}
	return written, nil
}

// ExportedVersion reads the stamp an Export left, or "" if there is none.
func ExportedVersion(dir string) string {
	raw, err := os.ReadFile(filepath.Join(dir, stampName))
	if err != nil {
		return ""
	}
	for _, line := range strings.Split(string(raw), "\n") {
		if v, ok := strings.CutPrefix(strings.TrimSpace(line), "version="); ok {
			return strings.TrimSpace(v)
		}
	}
	return ""
}

// NeedsExport reports whether dir must be (re)written for this build.
//
// True when the stamp is missing, belongs to another build, or the directory
// has lost chat.html -- the last because a tree someone half-deleted should be
// repaired rather than served with holes in it.
func NeedsExport(dir, version string) bool {
	if ExportedVersion(dir) != version {
		return true
	}
	if _, err := os.Stat(filepath.Join(dir, "chat.html")); err != nil {
		return true
	}
	return false
}
